name: Build and release

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            art-name: ex_linux-x86_64
            art-path: target/release/ex-rs
          - os: macos-13
            art-name: ex_macos-x86_64
            art-path: target/release/ex-rs
          - os: macos-14
            art-name: ex_macos-aarch64
            art-path: target/release/ex-rs
          - os: windows-2022
            art-name: ex_windows-x86_64
            art-path: target/release/ex-rs.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ art-name }}
          path: ${{ art-path }}
  release:
    needs: build
    strategy:
      matrix:
        os: [ex_linux-x86_64, ex_macos-x86_64, ex_macos-aarch64, ex_windows-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
      - run: echo "${{ matrix.os }}"
